# Food Insecurity in the United States

This notebook analyzes U.S. food insecurity using USDA ERS data, focusing on state differences and national patterns by education, employment, and disability status. It also uses World Bank undernourishment data for limited international context.

## 1. Introduction

Food insecurity is an important public health and economic issue in the U.S. This project uses USDA Economic Research Service data to analyze food insecurity by state, education, employment, and disability status.

The states chosen for comparison are California, Texas, Iowa, New York, and Louisiana. These states were selected because they are personally meaningful to me through family and other significant ties.

### Goals

The goals of this project are to:

1. Practice using Python and pandas.
2. Clean, inspect, prepare, and analyze real-world data.
3. Communicate findings and limitations.

### Data Questions

This analysis focuses on these questions:

1. How do food insecurity rates differ among California, Texas, Iowa, New York, and Louisiana?
2. How do selected states compare with the U.S. overall?
3. How does food insecurity vary by education level in the U.S.?
4. How does food insecurity vary by employment group in the U.S.?
5. How does food insecurity vary by disability status in the U.S.?
6. How does the U.S. compare with Canada and Mexico on undernourishment, and what World Bank metadata can be used to interpret that comparison?

## 2. Data Sources

The primary data source is USDA ERS Food Security in the U.S. data. This project uses state-level data, all-household data, and education/employment/disability data. World Bank undernourishment data is used as a secondary source for limited international context.

## 3. Setup and Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

## 4. Load the Data

#### Step 1: Add Path Setup

In [2]:
project_root = Path('..')

usda_dir = project_root / 'data' / 'raw' / 'usda_ers_food_security' / 'foodsecurity_csv_datafiles'
world_bank_dir = project_root / 'data' / 'raw' / 'world_bank_undernourishment'

#### Step 2: Load USDA Files

In [3]:
state_df = pd.read_csv(usda_dir / 'foodsecurity-state-2024.csv', encoding='cp1252')
all_households_df = pd.read_csv(usda_dir / 'foodsecurity-all-households-2024.csv', encoding='cp1252')
educ_emp_dis_df = pd.read_csv(usda_dir / 'foodsecurity-educ-emp-dis-2024.csv', encoding='cp1252')

#### Step 3: Load World Bank Files

In [4]:
wb_undernourishment_df = pd.read_csv(
    world_bank_dir / 'API_SN.ITK.DEFC.ZS_DS2_en_csv_v2_4749.csv',
    skiprows=4
)

wb_country_metadata_df = pd.read_csv(
    world_bank_dir / 'Metadata_Country_API_SN.ITK.DEFC.ZS_DS2_en_csv_v2_4749.csv'
)

wb_indicator_metadata_df = pd.read_csv(
    world_bank_dir / 'Metadata_Indicator_API_SN.ITK.DEFC.ZS_DS2_en_csv_v2_4749.csv'
)

## 5. Inspect the Data

### 5.1 Inspect `state_df`

In [5]:
state_df.head()

,Year,State,Food insecurity prevalence,Food insecurity–margin of error,Very low food security prevalence,Very low food security–margin of error
0,2006–2008,U.S. total,12.2,0.25,4.6,0.18
1,2006–2008,AK,11.6,1.66,4.4,1.31
2,2006–2008,AL,13.3,1.66,5.4,1.02
3,2006–2008,AR,15.9,3.19,5.6,1.50
4,2006–2008,AZ,13.2,1.51,4.9,0.84

In [6]:
state_df.shape

(884, 6)

In [7]:
state_df.columns

Index(['Year', 'State', 'Food insecurity prevalence',
       'Food insecurity–margin of error', 'Very low food security prevalence',
       'Very low food security–margin of error '],
      dtype='str')

In [8]:
state_df.isna().sum()

Year                                       0
State                                      0
Food insecurity prevalence                 0
Food insecurity–margin of error            0
Very low food security prevalence          0
Very low food security–margin of error     0
dtype: int64

In [9]:
state_df.duplicated().sum()

np.int64(0)

In [10]:
state_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 884 entries, 0 to 883
Data columns (total 6 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Year                                     884 non-null    str
 1   State                                    884 non-null    str
 2   Food insecurity prevalence               884 non-null    float64
 3   Food insecurity–margin of error          884 non-null    float64
 4   Very low food security prevalence        884 non-null    float64
 5   Very low food security–margin of error   884 non-null    float64
dtypes: float64(4), str(2)
memory usage: 41.6 KB

In [11]:
state_df.describe()

,Food insecurity prevalence,Food insecurity–margin of error,Very low food security prevalence,Very low food security–margin of error
count,884.000000,884.000000,884.000000,884.000000
mean,12.536991,1.533518,4.915498,0.946459
std,2.658856,0.466832,1.171112,0.293564
min,5.400000,0.190000,1.800000,0.100000
25%,10.600000,1.250000,4.100000,0.760000
50%,12.400000,1.520000,4.800000,0.930000
75%,14.325000,1.800000,5.700000,1.120000
max,22.000000,3.620000,9.000000,2.240000

In [12]:
state_df['Year'].value_counts()

Year
2006–2008    52
2007–2009    52
2008–2010    52
2009–2011    52
2010–2012    52
2011–2013    52
2012–2014    52
2013–2015    52
2014–2016    52
2015–2017    52
2016–2018    52
2017–2019    52
2018–2020    52
2019–2021    52
2020–2022    52
2021–2023    52
2022–2024    52
Name: count, dtype: int64

In [13]:
state_df['State'].value_counts()

State
AK            17
AL            17
AR            17
AZ            17
CA            17
CO            17
CT            17
DC            17
DE            17
FL            17
GA            17
HI            17
IA            17
ID            17
IL            17
IN            17
KS            17
KY            17
LA            17
MA            17
MD            17
ME            17
MI            17
MN            17
MO            17
MS            17
MT            17
NC            17
ND            17
NE            17
NH            17
NJ            17
NM            17
NV            17
NY            17
OH            17
OK            17
OR            17
PA            17
RI            17
SC            17
SD            17
TN            17
TX            17
UT            17
VA            17
VT            17
WA            17
WI            17
WV            17
WY            17
U.S.          16
U.S. total     1
Name: count, dtype: int64

### 5.2 Inspect `all_households_df`

In [14]:
all_households_df.head()

,Year,Category,Subcategory,Sub-subcategory,Total,"Food secure-1,000",Food secure-percent,"Food insecure-1,000",Food insecure-percent,"Low food security-1,000",Low food security-percent,"Very low food security-1,000",Very low food security-percent
0,2001,All households,NaN,NaN,107824,96303,89.3,11521,10.7,8010,7.4,3511,3.3
1,2001,Household composition,With children < 18 years,NaN,38330,32141,83.9,6189,16.1,4744,12.4,1445,3.8
2,2001,Household composition,With children < 18 years,With children < 6 years,16858,13920,82.6,2938,17.4,2304,13.7,634,3.8
3,2001,Household composition,With children < 18 years,Married-couple families,26182,23389,89.3,2793,10.7,2247,8.6,546,2.1
4,2001,Household composition,With children < 18 years,"Female head, no spouse",9080,6185,68.1,2895,31.9,2101,23.1,794,8.7

In [15]:
all_households_df.shape

(720, 13)

In [16]:
all_households_df.columns

Index(['Year', 'Category', 'Subcategory', 'Sub-subcategory', 'Total',
       'Food secure-1,000', 'Food secure-percent', 'Food insecure-1,000',
       'Food insecure-percent', 'Low food security-1,000',
       'Low food security-percent', 'Very low food security-1,000',
       'Very low food security-percent'],
      dtype='str')

In [17]:
all_households_df.isna().sum()

Year                                0
Category                            0
Subcategory                        24
Sub-subcategory                   456
Total                               0
Food secure-1,000                   0
Food secure-percent                 0
Food insecure-1,000                 0
Food insecure-percent               0
Low food security-1,000             7
Low food security-percent           8
Very low food security-1,000        5
Very low food security-percent      8
dtype: int64

In [18]:
all_households_df.duplicated().sum()

np.int64(0)

In [19]:
all_households_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Year                            720 non-null    int64
 1   Category                        720 non-null    str
 2   Subcategory                     696 non-null    str
 3   Sub-subcategory                 264 non-null    str
 4   Total                           720 non-null    int64
 5   Food secure-1,000               720 non-null    int64
 6   Food secure-percent             720 non-null    float64
 7   Food insecure-1,000             720 non-null    int64
 8   Food insecure-percent           720 non-null    float64
 9   Low food security-1,000         713 non-null    str
 10  Low food security-percent       712 non-null    float64
 11  Very low food security-1,000    715 non-null    str
 12  Very low food security-percent  712 non-null    float64
dtypes: float64(4), int64(4), str(5)
memory usage: 73.3 KB

In [20]:
all_households_df.describe()

,Year,Total,"Food secure-1,000",Food secure-percent,"Food insecure-1,000",Food insecure-percent,Low food security-percent,Very low food security-percent
count,720.000000,720.000000,720.000000,720.000000,720.000000,720.000000,712.000000,712.000000
mean,2012.500000,34506.366667,30002.370833,84.110417,4503.995833,15.889583,10.040871,5.822051
std,6.926999,29652.195835,26803.768658,8.646452,3471.945761,8.646452,5.461148,3.551875
min,2001.000000,413.000000,337.000000,57.000000,51.000000,4.900000,3.200000,0.800000
25%,2006.750000,15555.500000,11950.250000,81.000000,2441.000000,9.900000,6.000000,3.600000
50%,2012.500000,24963.500000,20492.000000,87.000000,3513.500000,13.000000,7.900000,4.800000
75%,2018.250000,43948.250000,39098.750000,90.100000,5994.500000,19.000000,13.200000,6.525000
max,2024.000000,134062.000000,118533.000000,95.100000,18340.000000,43.000000,25.300000,19.300000

In [21]:
all_households_df['Year'].value_counts()

Year
2001    30
2002    30
2003    30
2004    30
2005    30
2006    30
2007    30
2008    30
2009    30
2010    30
2011    30
2012    30
2013    30
2014    30
2015    30
2016    30
2017    30
2018    30
2019    30
2020    30
2021    30
2022    30
2023    30
2024    30
Name: count, dtype: int64

In [22]:
all_households_df['Category'].value_counts()

Category
Household composition                288
Household income-to-poverty ratio    120
Race/ethnicity of households          96
Area of residence                     96
Census geographic region              96
All households                        24
Name: count, dtype: int64

In [23]:
all_households_df['Subcategory'].value_counts()

Subcategory
With children < 18 years       144
With no children < 18 years     96
Inside metropolitan area        72
With elderly                    48
White non-Hispanic              24
Black non-Hispanic              24
Hispanic                        24
Other                           24
Under 1.00                      24
Under 1.30                      24
Under 1.85                      24
1.85 and over                   24
Income unknown                  24
Outside metropolitan area       24
Northeast                       24
Midwest                         24
South                           24
West                            24
Name: count, dtype: int64

In [24]:
all_households_df['Sub-subcategory'].value_counts()

Sub-subcategory
With children < 6 years       24
Married-couple families       24
Female head, no spouse        24
Male head, no spouse          24
Other household with child    24
More than one adult           24
Women living alone            24
Men living alone              24
Elderly living alone          24
In principal cities           24
Not in principal cities       24
Name: count, dtype: int64

### 5.3 Inspect `educ_emp_dis_df`

In [25]:
educ_emp_dis_df.head()

,Year,Category,Subcategory,Sub-subcategory,Total,"Food insecure-1,000",Food insecure-percent,Food insecure-share,"Very low food security-1,000",Very low food security-percent,Very low food security-share
0,2017,All households,NaN,NaN,127272,15018,11.8,100.0,5757,4.5,100.0
1,2017,All households,Employment,Full-time,83681,7871,9.4,52.4,2448,2.9,42.5
2,2017,All households,Employment,Retired,26903,2002,7.4,13.3,861,3.2,15.0
3,2017,All households,Employment,Part-time non-economic reasons,5673,1055,18.6,7.0,421,7.4,7.3
4,2017,All households,Employment,Part-time economic reasons,1162,447,38.5,3.0,168,14.4,2.9

In [26]:
educ_emp_dis_df.shape

(128, 11)

In [27]:
educ_emp_dis_df.columns

Index(['Year', 'Category', 'Subcategory', 'Sub-subcategory', 'Total',
       'Food insecure-1,000', 'Food insecure-percent', 'Food insecure-share',
       'Very low food security-1,000', 'Very low food security-percent',
       'Very low food security-share'],
      dtype='str')

In [28]:
educ_emp_dis_df.isna().sum()

Year                              0
Category                          0
Subcategory                       8
Sub-subcategory                   8
Total                             0
Food insecure-1,000               0
Food insecure-percent             0
Food insecure-share               0
Very low food security-1,000      0
Very low food security-percent    0
Very low food security-share      0
dtype: int64

In [29]:
educ_emp_dis_df.duplicated().sum()

np.int64(0)

In [30]:
educ_emp_dis_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Year                            128 non-null    int64
 1   Category                        128 non-null    str
 2   Subcategory                     120 non-null    str
 3   Sub-subcategory                 120 non-null    str
 4   Total                           128 non-null    int64
 5   Food insecure-1,000             128 non-null    int64
 6   Food insecure-percent           128 non-null    float64
 7   Food insecure-share             128 non-null    float64
 8   Very low food security-1,000    128 non-null    int64
 9   Very low food security-percent  128 non-null    float64
 10  Very low food security-share    128 non-null    float64
dtypes: float64(4), int64(4), str(3)
memory usage: 11.1 KB

In [31]:
educ_emp_dis_df.describe()

,Year,Total,"Food insecure-1,000",Food insecure-percent,Food insecure-share,"Very low food security-1,000",Very low food security-percent,Very low food security-share
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,2020.500000,32748.867188,3860.304688,20.905469,25.000781,1489.859375,9.170312,24.999219
std,2.300291,39303.864929,4004.054613,12.230267,25.490444,1474.454458,6.458960,24.234025
min,2017.000000,796.000000,282.000000,4.500000,1.700000,128.000000,1.500000,2.100000
25%,2018.750000,5320.000000,1054.500000,10.125000,6.975000,437.500000,3.575000,7.250000
50%,2020.500000,11343.500000,2175.000000,18.400000,14.550000,966.500000,7.300000,15.450000
75%,2022.250000,41312.500000,4953.000000,30.425000,33.750000,1991.000000,13.525000,34.225000
max,2024.000000,134062.000000,18341.000000,49.000000,100.000000,7202.000000,25.400000,100.000000

In [32]:
educ_emp_dis_df['Year'].value_counts()

Year
2017    16
2018    16
2019    16
2020    16
2021    16
2022    16
2023    16
2024    16
Name: count, dtype: int64

In [33]:
educ_emp_dis_df['Category'].value_counts()

Category
All households    128
Name: count, dtype: int64

In [34]:
educ_emp_dis_df['Subcategory'].value_counts()

Subcategory
Employment           56
Education            32
Disability status    32
Name: count, dtype: int64

In [35]:
educ_emp_dis_df['Sub-subcategory'].value_counts()

Sub-subcategory
Full-time                               8
Retired                                 8
Part-time non-economic reasons          8
Part-time economic reasons              8
Unemployed                              8
Disabled                                8
Not in labor force                      8
Less than high school                   8
High School                             8
Some College                            8
College or more                         8
Not in labor force due to disability    8
Other disability among adults 18-64     8
Other disability among adults 65+       8
No adult with disabilities              8
Name: count, dtype: int64

### 5.4 Inspect `wb_undernourishment_df`

In [36]:
wb_undernourishment_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.294658,23.490746,24.145274,24.993482,25.052183,26.160868,26.083778,NaN,NaN,NaN
2,Afghanistan,AFG,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,21.300000,22.600000,25.100000,27.500000,28.800000,28.900000,28.100000,NaN,NaN,NaN
3,Africa Western and Central,AFW,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,12.236478,12.416785,13.319356,13.907408,14.837060,15.529367,16.259131,NaN,NaN,NaN
4,Angola,AGO,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,15.400000,15.900000,18.200000,20.800000,22.600000,23.100000,22.500000,NaN,NaN,NaN

In [37]:
wb_undernourishment_df.shape

(265, 71)

In [38]:
wb_undernourishment_df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025', 'Unnamed: 70'],
      dtype='str')

In [39]:
wb_undernourishment_df.isna().sum()

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              265
                 ...
2022               52
2023               53
2024              265
2025              265
Unnamed: 70       265
Length: 71, dtype: int64

In [40]:
wb_undernourishment_df.duplicated().sum()

np.int64(0)

In [41]:
wb_undernourishment_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    265 non-null    str
 1   Country Code    265 non-null    str
 2   Indicator Name  265 non-null    str
 3   Indicator Code  265 non-null    str
 4   1960            0 non-null      float64
 5   1961            0 non-null      float64
 6   1962            0 non-null      float64
 7   1963            0 non-null      float64
 8   1964            0 non-null      float64
 9   1965            0 non-null      float64
 10  1966            0 non-null      float64
 11  1967            0 non-null      float64
 12  1968            0 non-null      float64
 13  1969            0 non-null      float64
 14  1970            0 non-null      float64
 15  1971            0 non-null      float64
 16  1972            0 non-null      float64
 17  1973            0 non-null      float64
 18  1974            0 non-null      float64
 19  1975            0 non-null      float64
 20  1976            0 non-null      float64
 21  1977            0 non-null      float64
 22  1978            0 non-null      float64
 23  1979            0 non-null      float64
 24  1980            0 non-null      float64
 25  1981            0 non-null      float64
 26  1982            0 non-null      float64
 27  1983            0 non-null      float64
 28  1984            0 non-null      float64
 29  1985            0 non-null      float64
 30  1986            0 non-null      float64
 31  1987            0 non-null      float64
 32  1988            0 non-null      float64
 33  1989            0 non-null      float64
 34  1990            0 non-null      float64
 35  1991            0 non-null      float64
 36  1992            0 non-null      float64
 37  1993            0 non-null      float64
 38  1994            0 non-null      float64
 39  1995            0 non-null      float64
 40  1996            0 non-null      float64
 41  1997            0 non-null      float64
 42  1998            0 non-null      float64
 43  1999            0 non-null      float64
 44  2000            0 non-null      float64
 45  2001            214 non-null    float64
 46  2002            214 non-null    float64
 47  2003            214 non-null    float64
 48  2004            214 non-null    float64
 49  2005            214 non-null    float64
 50  2006            214 non-null    float64
 51  2007            213 non-null    float64
 52  2008            213 non-null    float64
 53  2009            213 non-null    float64
 54  2010            213 non-null    float64
 55  2011            213 non-null    float64
 56  2012            213 non-null    float64
 57  2013            214 non-null    float64
 58  2014            214 non-null    float64
 59  2015            214 non-null    float64
 60  2016            214 non-null    float64
 61  2017            214 non-null    float64
 62  2018            214 non-null    float64
 63  2019            213 non-null    float64
 64  2020            214 non-null    float64
 65  2021            214 non-null    float64
 66  2022            213 non-null    float64
 67  2023            212 non-null    float64
 68  2024            0 non-null      float64
 69  2025            0 non-null      float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), str(4)
memory usage: 147.1 KB

In [42]:
wb_undernourishment_df['Country Name'].value_counts()

Country Name
Aruba                          1
Africa Eastern and Southern    1
Afghanistan                    1
Africa Western and Central     1
Angola                         1
                              ..
Kosovo                         1
Yemen, Rep.                    1
South Africa                   1
Zambia                         1
Zimbabwe                       1
Name: count, Length: 265, dtype: int64

In [43]:
wb_undernourishment_df['Country Code'].value_counts()

Country Code
ABW    1
AFE    1
AFG    1
AFW    1
AGO    1
      ..
XKX    1
YEM    1
ZAF    1
ZMB    1
ZWE    1
Name: count, Length: 265, dtype: int64

In [44]:
wb_undernourishment_df['Indicator Name'].value_counts()

Indicator Name
Prevalence of undernourishment (% of population)    265
Name: count, dtype: int64

In [45]:
wb_undernourishment_df['Indicator Code'].value_counts()

Indicator Code
SN.ITK.DEFC.ZS    265
Name: count, dtype: int64

### 5.5 Inspect `wb_country_metadata_df`

In [46]:
wb_country_metadata_df.head()

,Country Code,Region,IncomeGroup,SpecialNotes,TableName,Unnamed: 5
0,ABW,Latin America & Caribbean,High income,NaN,Aruba,NaN
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern,NaN
2,AFG,Middle East & North Africa,Low income,The reporting period for national accounts dat...,Afghanistan,NaN
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central,NaN
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola,NaN

In [47]:
wb_country_metadata_df.shape

(264, 6)

In [48]:
wb_country_metadata_df.columns

Index(['Country Code', 'Region', 'IncomeGroup', 'SpecialNotes', 'TableName',
       'Unnamed: 5'],
      dtype='str')

In [49]:
wb_country_metadata_df.isna().sum()

Country Code      0
Region           47
IncomeGroup      47
SpecialNotes    130
TableName         0
Unnamed: 5      264
dtype: int64

In [50]:
wb_country_metadata_df.duplicated().sum()

np.int64(0)

In [51]:
wb_country_metadata_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Code  264 non-null    str
 1   Region        217 non-null    str
 2   IncomeGroup   217 non-null    str
 3   SpecialNotes  134 non-null    str
 4   TableName     264 non-null    str
 5   Unnamed: 5    0 non-null      float64
dtypes: float64(1), str(5)
memory usage: 12.5 KB

In [52]:
wb_country_metadata_df['Country Code'].value_counts()

Country Code
ABW    1
AFE    1
AFG    1
AFW    1
AGO    1
      ..
XKX    1
YEM    1
ZAF    1
ZMB    1
ZWE    1
Name: count, Length: 264, dtype: int64

In [53]:
wb_country_metadata_df['Region'].value_counts()

Region
Europe & Central Asia         58
Sub-Saharan Africa            48
Latin America & Caribbean     42
East Asia & Pacific           37
Middle East & North Africa    23
South Asia                     6
North America                  3
Name: count, dtype: int64

In [54]:
wb_country_metadata_df['TableName'].value_counts()

TableName
Aruba                          1
Africa Eastern and Southern    1
Afghanistan                    1
Africa Western and Central     1
Angola                         1
                              ..
Kosovo                         1
Yemen, Rep.                    1
South Africa                   1
Zambia                         1
Zimbabwe                       1
Name: count, Length: 264, dtype: int64

### 5.6 Inspect `wb_indicator_metadata_df`

In [55]:
wb_indicator_metadata_df.head()

,INDICATOR_CODE,INDICATOR_NAME,SOURCE_NOTE,SOURCE_ORGANIZATION,Unnamed: 4
0,SN.ITK.DEFC.ZS,Prevalence of undernourishment (% of population),Prevalence of undernourishment is the percenta...,Food and Agriculture Organization of the Unite...,NaN

In [56]:
wb_indicator_metadata_df.shape

(1, 5)

In [57]:
wb_indicator_metadata_df.columns

Index(['INDICATOR_CODE', 'INDICATOR_NAME', 'SOURCE_NOTE',
       'SOURCE_ORGANIZATION', 'Unnamed: 4'],
      dtype='str')

In [58]:
wb_indicator_metadata_df.isna().sum()

INDICATOR_CODE         0
INDICATOR_NAME         0
SOURCE_NOTE            0
SOURCE_ORGANIZATION    0
Unnamed: 4             1
dtype: int64

In [59]:
wb_indicator_metadata_df.duplicated().sum()

np.int64(0)

In [60]:
wb_indicator_metadata_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   INDICATOR_CODE       1 non-null      str
 1   INDICATOR_NAME       1 non-null      str
 2   SOURCE_NOTE          1 non-null      str
 3   SOURCE_ORGANIZATION  1 non-null      str
 4   Unnamed: 4           0 non-null      float64
dtypes: float64(1), str(4)
memory usage: 172.0 bytes

### Inspection Notes

- USDA state data uses 3-year periods.
- Some column names are long and/or contain spaces or punctuation.
- World Bank undernourishment data is wide, with years stored as columns.
- World Bank data has an extra `Unnamed: ...` column at the end, for all 3 World Bank DataFrames.
    - In **6. Clean the Data**, we can drop these columns.
- Missing values exist in the following DataFrames:
    - `all_households_df`
    - `wb_undernourishment_df`
    - `wb_country_metadata_df`

**Are column names short and descriptive?**

- Column names are rather long and unwieldy in the case of the USDA dataset. Column names are reasonable, however.
    - We could rename these columns in **6. Clean the Data**.
- Column names are reasonably short and workable in the World Bank datasets.

**Are object columns consistently cased (lowercase, UPPERCASE, etc.)?**

- USDA data: No
- WB data: Yes

**Are numeric columns correctly typed as integers or floats?**

- USDA data: Mostly, though some numeric columns use `N/A`-style string placeholders that should be converted to true missing values.
- WB data: Yes

**Is there a significant amount of missing data?**

- USDA: Yes, but this is mostly for categorical columns for which a value may not be needed due to structure
- WB data: Yes, especially in the year columns.
- We can handle missing values in **6. Clean the Data**

**Are there duplicate rows?**

- No exact duplicate rows were found in the loaded DataFrames.

## 6. Clean the Data

### 6.1 Drop Extra `Unnamed: ...` Columns from World Bank Data

In [61]:
wb_undernourishment_df = wb_undernourishment_df.loc[:, ~wb_undernourishment_df.columns.str.startswith('Unnamed')]
wb_country_metadata_df = wb_country_metadata_df.loc[:, ~wb_country_metadata_df.columns.str.startswith('Unnamed')]
wb_indicator_metadata_df = wb_indicator_metadata_df.loc[:, ~wb_indicator_metadata_df.columns.str.startswith('Unnamed')]

print(wb_undernourishment_df.columns.tolist())
print('\n', wb_country_metadata_df.columns.tolist())
print('\n', wb_indicator_metadata_df.columns.tolist())

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

 ['Country Code', 'Region', 'IncomeGroup', 'SpecialNotes', 'TableName']

 ['INDICATOR_CODE', 'INDICATOR_NAME', 'SOURCE_NOTE', 'SOURCE_ORGANIZATION']

### 6.2 Standardize Column Names

#### I use a helper function to standardize column names across all DataFrames so later filtering, merging, and analysis are easier.

In [62]:
def clean_column_names(df):
    """
    Return a copy of a DataFrame with standardized column names.

    Column names are converted to lowercase, non-alphanumeric characters
    are replaced with underscores, and leading/trailing underscores are removed.
    """
    df = df.copy()
    
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(r'[^a-z0-9_]', '_', regex=True)
        .str.strip('_')
    )
    
    return df

In [63]:
state_df = clean_column_names(state_df)
all_households_df = clean_column_names(all_households_df)
educ_emp_dis_df = clean_column_names(educ_emp_dis_df)
wb_undernourishment_df = clean_column_names(wb_undernourishment_df)
wb_country_metadata_df = clean_column_names(wb_country_metadata_df)
wb_indicator_metadata_df = clean_column_names(wb_indicator_metadata_df)

In [64]:
for df in [state_df, all_households_df, educ_emp_dis_df]:
    print('\n', df.columns.tolist())

 ['year', 'state', 'food_insecurity_prevalence', 'food_insecurity_margin_of_error', 'very_low_food_security_prevalence', 'very_low_food_security_margin_of_error']

 ['year', 'category', 'subcategory', 'sub_subcategory', 'total', 'food_secure_1_000', 'food_secure_percent', 'food_insecure_1_000', 'food_insecure_percent', 'low_food_security_1_000', 'low_food_security_percent', 'very_low_food_security_1_000', 'very_low_food_security_percent']

 ['year', 'category', 'subcategory', 'sub_subcategory', 'total', 'food_insecure_1_000', 'food_insecure_percent', 'food_insecure_share', 'very_low_food_security_1_000', 'very_low_food_security_percent', 'very_low_food_security_share']

In [65]:
for df in [wb_undernourishment_df, wb_country_metadata_df, wb_indicator_metadata_df]:
    print('\n', df.columns.tolist())

 ['country_name', 'country_code', 'indicator_name', 'indicator_code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

 ['country_code', 'region', 'incomegroup', 'specialnotes', 'tablename']

 ['indicator_code', 'indicator_name', 'source_note', 'source_organization']

In the World Bank country metadata file, `tablename` appears to contain the readable country/economy name. I rename it here to `metadata_country_name` to make its meaning clearer and avoid confusion with `country_name` in the main World Bank data.

In [66]:
wb_country_metadata_df = wb_country_metadata_df.rename(
    {
        'tablename': 'metadata_country_name',
        'incomegroup': 'income_group',
        'specialnotes': 'special_notes'
    },
    axis=1
)

In [67]:
wb_country_metadata_df.columns.tolist()

['country_code',
 'region',
 'income_group',
 'special_notes',
 'metadata_country_name']

### 6.3 Review and Handle Missing Values

In [68]:
all_households_df[all_households_df['subcategory'].isna()].head(10)

,year,category,subcategory,sub_subcategory,total,food_secure_1_000,food_secure_percent,food_insecure_1_000,food_insecure_percent,low_food_security_1_000,low_food_security_percent,very_low_food_security_1_000,very_low_food_security_percent
0,2001,All households,NaN,NaN,107824,96303,89.3,11521,10.7,8010,7.4,3511,3.3
30,2002,All households,NaN,NaN,108601,96543,88.9,12058,11.1,8259,7.6,3799,3.5
60,2003,All households,NaN,NaN,112214,99631,88.8,12583,11.2,8663,7.7,3920,3.5
90,2004,All households,NaN,NaN,112967,99473,88.1,13494,11.9,9045,8.0,4449,3.9
120,2005,All households,NaN,NaN,114437,101851,89.0,12586,11.0,8158,7.1,4428,3.9
150,2006,All households,NaN,NaN,115609,102961,89.1,12648,10.9,8031,6.9,4617,4.0
180,2007,All households,NaN,NaN,117100,104089,88.9,13011,11.1,8262,7.0,4749,4.1
210,2008,All households,NaN,NaN,117565,100416,85.4,17149,14.6,10426,8.9,6723,5.7
240,2009,All households,NaN,NaN,118174,100820,85.3,17354,14.7,10601,9.0,6753,5.7
270,2010,All households,NaN,NaN,118756,101527,85.5,17229,14.5,10872,9.2,6357,5.4

In [69]:
all_households_df[all_households_df['sub_subcategory'].isna()].head(20)

,year,category,subcategory,sub_subcategory,total,food_secure_1_000,food_secure_percent,food_insecure_1_000,food_insecure_percent,low_food_security_1_000,low_food_security_percent,very_low_food_security_1_000,very_low_food_security_percent
0,2001,All households,NaN,NaN,107824,96303,89.3,11521,10.7,8010,7.4,3511,3.3
1,2001,Household composition,With children < 18 years,NaN,38330,32141,83.9,6189,16.1,4744,12.4,1445,3.8
7,2001,Household composition,With no children < 18 years,NaN,69495,64163,92.3,5332,7.7,3266,4.7,2066,3.0
11,2001,Household composition,With elderly,NaN,24836,23458,94.5,1378,5.5,1002,4.0,376,1.5
13,2001,Race/ethnicity of households,White non-Hispanic,NaN,80337,74230,92.4,6107,7.6,4072,5.1,2035,2.5
14,2001,Race/ethnicity of households,Black non-Hispanic,NaN,13134,10331,78.7,2803,21.3,1986,15.1,817,6.2
15,2001,Race/ethnicity of households,Hispanic,NaN,9864,7717,78.2,2147,21.8,1613,16.4,534,5.4
16,2001,Race/ethnicity of households,Other,NaN,4489,4026,89.7,463,10.3,339,7.6,124,2.8
17,2001,Household income-to-poverty ratio,Under 1.00,NaN,11693,7426,63.5,4267,36.5,2763,23.6,1504,12.9
18,2001,Household income-to-poverty ratio,Under 1.30,NaN,16904,11450,67.7,5454,32.3,3609,21.3,1845,10.9
19,2001,Household income-to-poverty ratio,Under 1.85,NaN,25395,18316,72.1,7079,27.9,4811,18.9,2268,8.9
20,2001,Household income-to-poverty ratio,1.85 and over,NaN,63851,60743,95.1,3108,4.9,2284,3.6,824,1.3
21,2001,Household income-to-poverty ratio,Income unknown,NaN,18579,17245,92.8,1334,7.2,915,4.9,419,2.3
22,2001,Area of residence,Inside metropolitan area,NaN,86945,77826,89.5,9119,10.5,6281,7.2,2838,3.3
25,2001,Area of residence,Outside metropolitan area,NaN,20879,18476,88.5,2403,11.5,1730,8.3,673,3.2
26,2001,Census geographic region,Northeast,NaN,20320,18656,91.8,1664,8.2,1176,5.8,488,2.4
27,2001,Census geographic region,Midwest,NaN,25063,22805,91.0,2258,9.0,1502,6.0,756,3.0
28,2001,Census geographic region,South,NaN,38867,34073,87.7,4794,12.3,3395,8.7,1399,3.6
29,2001,Census geographic region,West,NaN,23575,20771,88.1,2804,11.9,1937,8.2,867,3.7
30,2002,All households,NaN,NaN,108601,96543,88.9,12058,11.1,8259,7.6,3799,3.5

In [70]:
all_households_df[all_households_df['low_food_security_1_000'].isna()].head(10)

,year,category,subcategory,sub_subcategory,total,food_secure_1_000,food_secure_percent,food_insecure_1_000,food_insecure_percent,low_food_security_1_000,low_food_security_percent,very_low_food_security_1_000,very_low_food_security_percent
486,2017,Household composition,With children < 18 years,Other household with child,581,476,81.9,105,18.1,NaN,NaN,NaN,NaN
516,2018,Household composition,With children < 18 years,Other household with child,427,337,78.9,90,21.1,NaN,NaN,NaN,NaN
546,2019,Household composition,With children < 18 years,Other household with child,572,472,82.5,100,17.5,NaN,NaN,NaN,NaN
576,2020,Household composition,With children < 18 years,Other household with child,413,362,87.7,51,12.3,NaN,NaN,NaN,NaN
606,2021,Household composition,With children < 18 years,Other household with child,524,438,83.6,86,16.4,NaN,NaN,NaN,NaN
636,2022,Household composition,With children < 18 years,Other household with child,439,358,81.5,81,18.5,NaN,NaN,N/A,NaN
666,2023,Household composition,With children < 18 years,Other household with child,425,342,80.5,83,19.5,NaN,NaN,N/A,NaN

In [71]:
all_households_df[all_households_df['low_food_security_percent'].isna()].head(10)

,year,category,subcategory,sub_subcategory,total,food_secure_1_000,food_secure_percent,food_insecure_1_000,food_insecure_percent,low_food_security_1_000,low_food_security_percent,very_low_food_security_1_000,very_low_food_security_percent
456,2016,Household composition,With children < 18 years,Other household with child,519,404,77.8,115,22.2,N/A,NaN,N/A,NaN
486,2017,Household composition,With children < 18 years,Other household with child,581,476,81.9,105,18.1,NaN,NaN,NaN,NaN
516,2018,Household composition,With children < 18 years,Other household with child,427,337,78.9,90,21.1,NaN,NaN,NaN,NaN
546,2019,Household composition,With children < 18 years,Other household with child,572,472,82.5,100,17.5,NaN,NaN,NaN,NaN
576,2020,Household composition,With children < 18 years,Other household with child,413,362,87.7,51,12.3,NaN,NaN,NaN,NaN
606,2021,Household composition,With children < 18 years,Other household with child,524,438,83.6,86,16.4,NaN,NaN,NaN,NaN
636,2022,Household composition,With children < 18 years,Other household with child,439,358,81.5,81,18.5,NaN,NaN,N/A,NaN
666,2023,Household composition,With children < 18 years,Other household with child,425,342,80.5,83,19.5,NaN,NaN,N/A,NaN

In [72]:
all_households_df[all_households_df['very_low_food_security_1_000'].isna()].head(10)

,year,category,subcategory,sub_subcategory,total,food_secure_1_000,food_secure_percent,food_insecure_1_000,food_insecure_percent,low_food_security_1_000,low_food_security_percent,very_low_food_security_1_000,very_low_food_security_percent
486,2017,Household composition,With children < 18 years,Other household with child,581,476,81.9,105,18.1,NaN,NaN,NaN,NaN
516,2018,Household composition,With children < 18 years,Other household with child,427,337,78.9,90,21.1,NaN,NaN,NaN,NaN
546,2019,Household composition,With children < 18 years,Other household with child,572,472,82.5,100,17.5,NaN,NaN,NaN,NaN
576,2020,Household composition,With children < 18 years,Other household with child,413,362,87.7,51,12.3,NaN,NaN,NaN,NaN
606,2021,Household composition,With children < 18 years,Other household with child,524,438,83.6,86,16.4,NaN,NaN,NaN,NaN

In [73]:
all_households_df[all_households_df['very_low_food_security_percent'].isna()].head(10)

,year,category,subcategory,sub_subcategory,total,food_secure_1_000,food_secure_percent,food_insecure_1_000,food_insecure_percent,low_food_security_1_000,low_food_security_percent,very_low_food_security_1_000,very_low_food_security_percent
456,2016,Household composition,With children < 18 years,Other household with child,519,404,77.8,115,22.2,N/A,NaN,N/A,NaN
486,2017,Household composition,With children < 18 years,Other household with child,581,476,81.9,105,18.1,NaN,NaN,NaN,NaN
516,2018,Household composition,With children < 18 years,Other household with child,427,337,78.9,90,21.1,NaN,NaN,NaN,NaN
546,2019,Household composition,With children < 18 years,Other household with child,572,472,82.5,100,17.5,NaN,NaN,NaN,NaN
576,2020,Household composition,With children < 18 years,Other household with child,413,362,87.7,51,12.3,NaN,NaN,NaN,NaN
606,2021,Household composition,With children < 18 years,Other household with child,524,438,83.6,86,16.4,NaN,NaN,NaN,NaN
636,2022,Household composition,With children < 18 years,Other household with child,439,358,81.5,81,18.5,NaN,NaN,N/A,NaN
666,2023,Household composition,With children < 18 years,Other household with child,425,342,80.5,83,19.5,NaN,NaN,N/A,NaN

In [74]:
educ_emp_dis_df[educ_emp_dis_df['subcategory'].isna()].head(20)

,year,category,subcategory,sub_subcategory,total,food_insecure_1_000,food_insecure_percent,food_insecure_share,very_low_food_security_1_000,very_low_food_security_percent,very_low_food_security_share
0,2017,All households,NaN,NaN,127272,15018,11.8,100.0,5757,4.5,100.0
16,2018,All households,NaN,NaN,129245,14311,11.1,100.0,5581,4.3,100.0
32,2019,All households,NaN,NaN,129621,13662,10.5,100.0,5322,4.1,100.0
48,2020,All households,NaN,NaN,130459,13754,10.5,100.0,5141,3.9,100.0
64,2021,All households,NaN,NaN,132043,13510,10.2,100.0,5082,3.8,100.0
80,2022,All households,NaN,NaN,132730,16980,12.8,100.0,6793,5.1,100.0
96,2023,All households,NaN,NaN,132532,17955,13.5,100.0,6799,5.1,100.0
112,2024,All households,NaN,NaN,134062,18341,13.7,100.0,7202,5.4,100.0

In [75]:
wb_undernourishment_df[wb_undernourishment_df['2000'].isna()].head()

,country_name,country_code,indicator_name,indicator_code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.029439,23.294658,23.490746,24.145274,24.993482,25.052183,26.160868,26.083778,NaN,NaN
2,Afghanistan,AFG,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,20.400000,21.300000,22.600000,25.100000,27.500000,28.800000,28.900000,28.100000,NaN,NaN
3,Africa Western and Central,AFW,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,12.022279,12.236478,12.416785,13.319356,13.907408,14.837060,15.529367,16.259131,NaN,NaN
4,Angola,AGO,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,15.200000,15.400000,15.900000,18.200000,20.800000,22.600000,23.100000,22.500000,NaN,NaN

In [76]:
wb_country_metadata_df[
    wb_country_metadata_df['region'].isna()
][['country_code', 'metadata_country_name', 'region', 'income_group']].head(20)

,country_code,metadata_country_name,region,income_group
1,AFE,Africa Eastern and Southern,NaN,NaN
3,AFW,Africa Western and Central,NaN,NaN
7,ARB,Arab World,NaN,NaN
36,CEB,Central Europe and the Baltics,NaN,NaN
49,CSS,Caribbean small states,NaN,NaN
61,EAP,East Asia & Pacific (excluding high income),NaN,NaN
62,EAR,Early-demographic dividend,NaN,NaN
63,EAS,East Asia & Pacific,NaN,NaN
64,ECA,Europe & Central Asia (excluding high income),NaN,NaN
65,ECS,Europe & Central Asia,NaN,NaN
68,EMU,Euro area,NaN,NaN
73,EUU,European Union,NaN,NaN
94,HIC,High income,NaN,NaN
97,HPC,Heavily indebted poor countries (HIPC),NaN,NaN
101,IBD,IBRD only,NaN,NaN
102,IBT,IDA & IBRD total,NaN,NaN
103,IDA,IDA total,NaN,NaN
104,IDB,IDA blend,NaN,NaN
106,IDX,IDA only,NaN,NaN
126,LAC,Latin America & Caribbean (excluding high income),NaN,NaN

In [77]:
wb_country_metadata_df[
    wb_country_metadata_df['income_group'].isna()
][['country_code', 'metadata_country_name', 'region', 'income_group']].head(20)

,country_code,metadata_country_name,region,income_group
1,AFE,Africa Eastern and Southern,NaN,NaN
3,AFW,Africa Western and Central,NaN,NaN
7,ARB,Arab World,NaN,NaN
36,CEB,Central Europe and the Baltics,NaN,NaN
49,CSS,Caribbean small states,NaN,NaN
61,EAP,East Asia & Pacific (excluding high income),NaN,NaN
62,EAR,Early-demographic dividend,NaN,NaN
63,EAS,East Asia & Pacific,NaN,NaN
64,ECA,Europe & Central Asia (excluding high income),NaN,NaN
65,ECS,Europe & Central Asia,NaN,NaN
68,EMU,Euro area,NaN,NaN
73,EUU,European Union,NaN,NaN
94,HIC,High income,NaN,NaN
97,HPC,Heavily indebted poor countries (HIPC),NaN,NaN
101,IBD,IBRD only,NaN,NaN
102,IBT,IDA & IBRD total,NaN,NaN
103,IDA,IDA total,NaN,NaN
104,IDB,IDA blend,NaN,NaN
106,IDX,IDA only,NaN,NaN
126,LAC,Latin America & Caribbean (excluding high income),NaN,NaN

In [78]:
wb_country_metadata_df['region'].isna().equals(
    wb_country_metadata_df['income_group'].isna()
)

True

In [79]:
wb_country_metadata_df[
    wb_country_metadata_df['region'].isna()
][['country_code', 'metadata_country_name', 'region', 'income_group']]

,country_code,metadata_country_name,region,income_group
1,AFE,Africa Eastern and Southern,NaN,NaN
3,AFW,Africa Western and Central,NaN,NaN
7,ARB,Arab World,NaN,NaN
36,CEB,Central Europe and the Baltics,NaN,NaN
49,CSS,Caribbean small states,NaN,NaN
61,EAP,East Asia & Pacific (excluding high income),NaN,NaN
62,EAR,Early-demographic dividend,NaN,NaN
63,EAS,East Asia & Pacific,NaN,NaN
64,ECA,Europe & Central Asia (excluding high income),NaN,NaN
65,ECS,Europe & Central Asia,NaN,NaN
68,EMU,Euro area,NaN,NaN
73,EUU,European Union,NaN,NaN
94,HIC,High income,NaN,NaN
97,HPC,Heavily indebted poor countries (HIPC),NaN,NaN
101,IBD,IBRD only,NaN,NaN
102,IBT,IDA & IBRD total,NaN,NaN
103,IDA,IDA total,NaN,NaN
104,IDB,IDA blend,NaN,NaN
106,IDX,IDA only,NaN,NaN
126,LAC,Latin America & Caribbean (excluding high income),NaN,NaN
132,LCN,Latin America & Caribbean,NaN,NaN
133,LDC,Least developed countries: UN classification,NaN,NaN
134,LIC,Low income,NaN,NaN
137,LMC,Lower middle income,NaN,NaN
138,LMY,Low & middle income,NaN,NaN
140,LTE,Late-demographic dividend,NaN,NaN
151,MEA,"Middle East, North Africa, Afghanistan & Pakistan",NaN,NaN
154,MIC,Middle income,NaN,NaN
159,MNA,"Middle East, North Africa, Afghanistan & Pakis...",NaN,NaN
168,NAC,North America,NaN,NaN
179,OED,OECD members,NaN,NaN
181,OSS,Other small states,NaN,NaN
189,PRE,Pre-demographic dividend,NaN,NaN
195,PSS,Pacific island small states,NaN,NaN
196,PST,Post-demographic dividend,NaN,NaN
202,SAS,South Asia,NaN,NaN
213,SSA,Sub-Saharan Africa (excluding high income),NaN,NaN
215,SSF,Sub-Saharan Africa,NaN,NaN
216,SST,Small states,NaN,NaN
228,TEA,East Asia & Pacific (IDA & IBRD),NaN,NaN
229,TEC,Europe & Central Asia (IDA & IBRD),NaN,NaN
234,TLA,Latin America & Caribbean (IDA & IBRD),NaN,NaN
236,TMN,"Middle East, North Africa, Afghanistan & Pakis...",NaN,NaN
238,TSA,South Asia (IDA & IBRD),NaN,NaN
239,TSS,Sub-Saharan Africa (IDA & IBRD),NaN,NaN
247,UMC,Upper middle income,NaN,NaN
257,WLD,World,NaN,NaN

In [80]:
wb_country_metadata_df[
    wb_country_metadata_df['income_group'].isna()
][['country_code', 'metadata_country_name', 'region', 'income_group']]

,country_code,metadata_country_name,region,income_group
1,AFE,Africa Eastern and Southern,NaN,NaN
3,AFW,Africa Western and Central,NaN,NaN
7,ARB,Arab World,NaN,NaN
36,CEB,Central Europe and the Baltics,NaN,NaN
49,CSS,Caribbean small states,NaN,NaN
61,EAP,East Asia & Pacific (excluding high income),NaN,NaN
62,EAR,Early-demographic dividend,NaN,NaN
63,EAS,East Asia & Pacific,NaN,NaN
64,ECA,Europe & Central Asia (excluding high income),NaN,NaN
65,ECS,Europe & Central Asia,NaN,NaN
68,EMU,Euro area,NaN,NaN
73,EUU,European Union,NaN,NaN
94,HIC,High income,NaN,NaN
97,HPC,Heavily indebted poor countries (HIPC),NaN,NaN
101,IBD,IBRD only,NaN,NaN
102,IBT,IDA & IBRD total,NaN,NaN
103,IDA,IDA total,NaN,NaN
104,IDB,IDA blend,NaN,NaN
106,IDX,IDA only,NaN,NaN
126,LAC,Latin America & Caribbean (excluding high income),NaN,NaN
132,LCN,Latin America & Caribbean,NaN,NaN
133,LDC,Least developed countries: UN classification,NaN,NaN
134,LIC,Low income,NaN,NaN
137,LMC,Lower middle income,NaN,NaN
138,LMY,Low & middle income,NaN,NaN
140,LTE,Late-demographic dividend,NaN,NaN
151,MEA,"Middle East, North Africa, Afghanistan & Pakistan",NaN,NaN
154,MIC,Middle income,NaN,NaN
159,MNA,"Middle East, North Africa, Afghanistan & Pakis...",NaN,NaN
168,NAC,North America,NaN,NaN
179,OED,OECD members,NaN,NaN
181,OSS,Other small states,NaN,NaN
189,PRE,Pre-demographic dividend,NaN,NaN
195,PSS,Pacific island small states,NaN,NaN
196,PST,Post-demographic dividend,NaN,NaN
202,SAS,South Asia,NaN,NaN
213,SSA,Sub-Saharan Africa (excluding high income),NaN,NaN
215,SSF,Sub-Saharan Africa,NaN,NaN
216,SST,Small states,NaN,NaN
228,TEA,East Asia & Pacific (IDA & IBRD),NaN,NaN
229,TEC,Europe & Central Asia (IDA & IBRD),NaN,NaN
234,TLA,Latin America & Caribbean (IDA & IBRD),NaN,NaN
236,TMN,"Middle East, North Africa, Afghanistan & Pakis...",NaN,NaN
238,TSA,South Asia (IDA & IBRD),NaN,NaN
239,TSS,Sub-Saharan Africa (IDA & IBRD),NaN,NaN
247,UMC,Upper middle income,NaN,NaN
257,WLD,World,NaN,NaN

In [81]:
wb_country_metadata_df[
    wb_country_metadata_df['special_notes'].isna()
][['country_code', 'metadata_country_name', 'region', 'special_notes', 'income_group']]

,country_code,metadata_country_name,region,special_notes,income_group
0,ABW,Aruba,Latin America & Caribbean,NaN,High income
5,ALB,Albania,Europe & Central Asia,NaN,Upper middle income
6,AND,Andorra,Europe & Central Asia,NaN,High income
8,ARE,United Arab Emirates,Middle East & North Africa,NaN,High income
10,ARM,Armenia,Europe & Central Asia,NaN,Upper middle income
...,...,...,...,...,...
254,VIR,Virgin Islands (US),Latin America & Caribbean,NaN,High income
255,VNM,Viet Nam,East Asia & Pacific,NaN,Upper middle income
256,VUT,Vanuatu,East Asia & Pacific,NaN,Lower middle income
257,WLD,World,NaN,NaN,NaN
259,XKX,Kosovo,Europe & Central Asia,NaN,Upper middle income

#### Significance of missing values
- USDA category columns: likely “not applicable”
- USDA low / very low food security columns: values not reported for those row categories
- World Bank year columns: data not available
- World Bank metadata `region`/`income_group` columns: aggregate / non-country entries, or not applicable
    - For aggregate rows, `metadata_country_name` describes the aggregate better than `region` or `income_group` would.
- World Bank special notes: no note provided

#### Appropriate handling of missing values

I will not fill missing values globally. Instead:
- USDA category columns: leave blank, because they are not applicable
- USDA low / very low food security columns: leave blank, because they are not equivalent to zero and values should not be interpolated
- World Bank year value columns: leave blank, because missing data is not equivalent to zero and values should not be interpolated
- World Bank `region` / `income_group` columns: leave blank, because they correspond to aggregate or non-country entities, or are not applicable
- World Bank `special_notes` column: leave blank, because lack of note just means 'no comment', and there is no need to fill this note

#### Handle 'N/A'-like values
- `all_households_df`
    - `low_food_security_1_000`
    - `low_food_security_percent`
    - `very_low_food_security_1_000`
    - `very_low_food_security_percent`

Some USDA numeric columns contain `N/A`-style string placeholders. I convert those placeholders to true missing values, convert the count columns to nullable integers, and keep percentage columns as floats. I do not impute, interpolate, or replace these values with zero.

In [82]:
count_na_columns = [
    'low_food_security_1_000',
    'very_low_food_security_1_000'
]

percent_na_columns = [
    'low_food_security_percent',
    'very_low_food_security_percent'
]

all_households_df[count_na_columns] = (
    all_households_df[count_na_columns]
    .replace(r'^\s*N/A\s*$', np.nan, regex=True)
    .apply(pd.to_numeric, errors='coerce')
    .astype('Int64')
)

all_households_df[percent_na_columns] = (
    all_households_df[percent_na_columns]
    .replace(r'^\s*N/A\s*$', np.nan, regex=True)
    .apply(pd.to_numeric, errors='coerce')
)

In [83]:
dataframes_to_check = {
    'state_df': state_df,
    'all_households_df': all_households_df,
    'educ_emp_dis_df': educ_emp_dis_df,
    'wb_undernourishment_df': wb_undernourishment_df,
    'wb_country_metadata_df': wb_country_metadata_df,
    'wb_indicator_metadata_df': wb_indicator_metadata_df
}

In [84]:
na_like_pattern = r'^\s*N/A\s*$'

na_like_summary = []

for df_name, df in dataframes_to_check.items():
    na_like_counts = (
        df.astype('string')
        .apply(lambda col: col.str.match(na_like_pattern, na=False))
        .sum()
    )

    for column_name, count in na_like_counts[na_like_counts > 0].items():
        na_like_summary.append({
            'dataframe': df_name,
            'column': column_name,
            'n_a_like_count': count
        })

na_like_summary_df = pd.DataFrame(na_like_summary)

if na_like_summary_df.empty:
    print('No N/A-like string values found in any DataFrame.')
else:
    display(na_like_summary_df)

No N/A-like string values found in any DataFrame.

In [85]:
na_columns = count_na_columns + percent_na_columns

all_households_df[na_columns].isna().sum()

low_food_security_1_000           8
very_low_food_security_1_000      8
low_food_security_percent         8
very_low_food_security_percent    8
dtype: int64

In [86]:
all_households_df[na_columns].dtypes

low_food_security_1_000             Int64
very_low_food_security_1_000        Int64
low_food_security_percent         float64
very_low_food_security_percent    float64
dtype: object

### 6.4 Confirm Cleaned DataFrames Still Have Expected Structure

In [87]:
cleaned_dataframes = {
    'state_df': state_df,
    'all_households_df': all_households_df,
    'educ_emp_dis_df': educ_emp_dis_df,
    'wb_undernourishment_df': wb_undernourishment_df,
    'wb_country_metadata_df': wb_country_metadata_df,
    'wb_indicator_metadata_df': wb_indicator_metadata_df
}

In [88]:
for df_name, df in cleaned_dataframes.items():
    print(df_name, df.shape)

state_df (884, 6)
all_households_df (720, 13)
educ_emp_dis_df (128, 11)
wb_undernourishment_df (265, 70)
wb_country_metadata_df (264, 5)
wb_indicator_metadata_df (1, 4)

In [89]:
for df_name, df in cleaned_dataframes.items():
    print(f'\n{df_name}')
    print(df.columns.tolist())

state_df
['year', 'state', 'food_insecurity_prevalence', 'food_insecurity_margin_of_error', 'very_low_food_security_prevalence', 'very_low_food_security_margin_of_error']

all_households_df
['year', 'category', 'subcategory', 'sub_subcategory', 'total', 'food_secure_1_000', 'food_secure_percent', 'food_insecure_1_000', 'food_insecure_percent', 'low_food_security_1_000', 'low_food_security_percent', 'very_low_food_security_1_000', 'very_low_food_security_percent']

educ_emp_dis_df
['year', 'category', 'subcategory', 'sub_subcategory', 'total', 'food_insecure_1_000', 'food_insecure_percent', 'food_insecure_share', 'very_low_food_security_1_000', 'very_low_food_security_percent', 'very_low_food_security_share']

wb_undernourishment_df
['country_name', 'country_code', 'indicator_name', 'indicator_code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

wb_country_metadata_df
['country_code', 'region', 'income_group', 'special_notes', 'metadata_country_name']

wb_indicator_metadata_df
['indicator_code', 'indicator_name', 'source_note', 'source_organization']

In [90]:
for df_name, df in cleaned_dataframes.items():
    print(f'\n{df_name}')
    print(df.dtypes)

state_df
year                                          str
state                                         str
food_insecurity_prevalence                float64
food_insecurity_margin_of_error           float64
very_low_food_security_prevalence         float64
very_low_food_security_margin_of_error    float64
dtype: object

all_households_df
year                                int64
category                              str
subcategory                           str
sub_subcategory                       str
total                               int64
food_secure_1_000                   int64
food_secure_percent               float64
food_insecure_1_000                 int64
food_insecure_percent             float64
low_food_security_1_000             Int64
low_food_security_percent         float64
very_low_food_security_1_000        Int64
very_low_food_security_percent    float64
dtype: object

educ_emp_dis_df
year                                int64
category                              str
subcategory                           str
sub_subcategory                       str
total                               int64
food_insecure_1_000                 int64
food_insecure_percent             float64
food_insecure_share               float64
very_low_food_security_1_000        int64
very_low_food_security_percent    float64
very_low_food_security_share      float64
dtype: object

wb_undernourishment_df
country_name          str
country_code          str
indicator_name        str
indicator_code        str
1960              float64
                   ...
2021              float64
2022              float64
2023              float64
2024              float64
2025              float64
Length: 70, dtype: object

wb_country_metadata_df
country_code             str
region                   str
income_group             str
special_notes            str
metadata_country_name    str
dtype: object

wb_indicator_metadata_df
indicator_code         str
indicator_name         str
source_note            str
source_organization    str
dtype: object

#### **Cleaning Summary**

At this point, the core cleaning is considered complete. I standardized column names, removed extra World Bank columns, added clarity to certain metadata column names, converted `N/A`-style strings to true missing values, and confirmed expected structure (shapes, columns, and data types).

I did not create new derived columns during general cleaning. I will create analysis-specific columns, such as period start/end years or reshaped year fields, in the preparation section when they are needed for specific data questions.

## 7. Prepare Analysis Tables

In this section, I build analysis-ready DataFrames from the cleaned data.

These tables are designed to be better suited to answering the project questions than the original source tables. The prepared tables may be smaller, reshaped, filtered, combined, or enriched with derived columns depending on the analysis need. The goal is to transform source tables until each one contains the data needed for analysis, with as little unnecessary detail as possible.

Planned analysis tables:

| DataFrame | Source | Purpose |
|---|---|---|
|`state_comparison_df`|`state_df`| Compare food insecurity rates across households in California, Texas, Iowa, New York, and Louisiana. |
|`state_us_comparison_df`|`state_comparison_df`, `all_households_df`| Compare selected state three-year food insecurity estimates with U.S. annual estimates, aligned by each period's ending year.|
|`educ_analysis_df`|`educ_emp_dis_df`| Analyze food insecurity rates across education groups within the U.S. |
|`emp_analysis_df`|`educ_emp_dis_df`| Identify which U.S. household employment categories have the highest food-insecurity prevalence. |
|`dis_analysis_df`|`educ_emp_dis_df`| Analyze food insecurity rates across disability groups within the U.S. |
|`wb_context_df`|`wb_undernourishment_df`, `wb_country_metadata_df`, `wb_indicator_metadata_df`| Compare U.S., Canada, and Mexico undernourishment using World Bank / FAO undernourishment data. |

### 7.1 Prepare Analysis Table `state_comparison_df` from `state_df`

In [91]:
# define selected states
selected_states = [
    'CA','IA','LA','NY','TX'
]

is_selected_state = state_df['state'].isin(selected_states)


state_comparison_df = state_df.loc[is_selected_state].copy()

display(state_comparison_df)

,year,state,food_insecurity_prevalence,food_insecurity_margin_of_error,very_low_food_security_prevalence,very_low_food_security_margin_of_error
5,2006–2008,CA,12.0,0.74,4.3,0.48
13,2006–2008,IA,11.6,1.15,4.8,0.93
19,2006–2008,LA,11.0,1.62,3.7,1.16
35,2006–2008,NY,11.3,0.95,4.3,0.46
44,2006–2008,TX,16.3,1.08,5.7,0.56
...,...,...,...,...,...,...
837,2022–2024,CA,12.5,0.82,4.4,0.49
845,2022–2024,IA,10.8,2.02,3.9,1.07
851,2022–2024,LA,17.7,2.29,6.8,1.24
867,2022–2024,NY,14.0,1.29,5.6,0.85
876,2022–2024,TX,17.6,1.01,6.6,0.63

In [92]:
period_years = state_comparison_df['year'].str.split(
    pat='–',
    expand=True,
    regex=False
)

In [93]:
state_comparison_df['period_start_year'] = period_years[0].astype('int64')
state_comparison_df['period_end_year'] = period_years[1].astype('int64')

### Validate `state_comparison_df`

In [94]:
state_comparison_df.shape

(85, 8)

In [95]:
print(state_comparison_df['state'].value_counts())
print('-----------------------------')
print('number of unique state values')
print(state_comparison_df['state'].nunique())

state
CA    17
IA    17
LA    17
NY    17
TX    17
Name: count, dtype: int64
-----------------------------
number of unique state values
5

In [96]:
state_comparison_df.groupby('state')['year'].nunique()

state
CA    17
IA    17
LA    17
NY    17
TX    17
Name: year, dtype: int64

In [97]:
state_comparison_df.info()

<class 'pandas.DataFrame'>
Index: 85 entries, 5 to 876
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   year                                    85 non-null     str
 1   state                                   85 non-null     str
 2   food_insecurity_prevalence              85 non-null     float64
 3   food_insecurity_margin_of_error         85 non-null     float64
 4   very_low_food_security_prevalence       85 non-null     float64
 5   very_low_food_security_margin_of_error  85 non-null     float64
 6   period_start_year                       85 non-null     int64
 7   period_end_year                         85 non-null     int64
dtypes: float64(4), int64(2), str(2)
memory usage: 6.0 KB

In [98]:
state_comparison_df.isna().sum()

year                                      0
state                                     0
food_insecurity_prevalence                0
food_insecurity_margin_of_error           0
very_low_food_security_prevalence         0
very_low_food_security_margin_of_error    0
period_start_year                         0
period_end_year                           0
dtype: int64

Validation looks good for `state_comparison_df`:
- 85 rows
- 8 columns
- No missing values
- Derived year columns are int64
- Prevalence / margin columns are numeric
- Note: year stays as string, which is correct because it’s a USDA 3-year label like `2006–2008`.

Because USDA state estimates are reported as 3-year periods while the U.S. overall `all_households_df` year column is reported annually, this comparison aligns each state period with the U.S. row for the state period end year. For example, `2022–2024` is compared with the U.S. overall estimate for `2024`.

### 7.2 Prepare Analysis Table `state_us_comparison_df` from `state_comparison_df` and `all_households_df`

In [99]:
all_households_df['category'].value_counts()

category
Household composition                288
Household income-to-poverty ratio    120
Race/ethnicity of households          96
Area of residence                     96
Census geographic region              96
All households                        24
Name: count, dtype: int64

In [100]:
all_households_df[['category','subcategory','sub_subcategory']].drop_duplicates()

,category,subcategory,sub_subcategory
0,All households,NaN,NaN
1,Household composition,With children < 18 years,NaN
2,Household composition,With children < 18 years,With children < 6 years
3,Household composition,With children < 18 years,Married-couple families
4,Household composition,With children < 18 years,"Female head, no spouse"
5,Household composition,With children < 18 years,"Male head, no spouse"
6,Household composition,With children < 18 years,Other household with child
7,Household composition,With no children < 18 years,NaN
8,Household composition,With no children < 18 years,More than one adult
9,Household composition,With no children < 18 years,Women living alone
10,Household composition,With no children < 18 years,Men living alone
11,Household composition,With elderly,NaN
12,Household composition,With elderly,Elderly living alone
13,Race/ethnicity of households,White non-Hispanic,NaN
14,Race/ethnicity of households,Black non-Hispanic,NaN
15,Race/ethnicity of households,Hispanic,NaN
16,Race/ethnicity of households,Other,NaN
17,Household income-to-poverty ratio,Under 1.00,NaN
18,Household income-to-poverty ratio,Under 1.30,NaN
19,Household income-to-poverty ratio,Under 1.85,NaN
20,Household income-to-poverty ratio,1.85 and over,NaN
21,Household income-to-poverty ratio,Income unknown,NaN
22,Area of residence,Inside metropolitan area,NaN
23,Area of residence,Inside metropolitan area,In principal cities
24,Area of residence,Inside metropolitan area,Not in principal cities
25,Area of residence,Outside metropolitan area,NaN
26,Census geographic region,Northeast,NaN
27,Census geographic region,Midwest,NaN
28,Census geographic region,South,NaN
29,Census geographic region,West,NaN

In [101]:
all_households_df[
    all_households_df['category'].str.contains('total|all|household', case=False, na=False)
]

,year,category,subcategory,sub_subcategory,total,food_secure_1_000,food_secure_percent,food_insecure_1_000,food_insecure_percent,low_food_security_1_000,low_food_security_percent,very_low_food_security_1_000,very_low_food_security_percent
0,2001,All households,NaN,NaN,107824,96303,89.3,11521,10.7,8010,7.4,3511,3.3
1,2001,Household composition,With children < 18 years,NaN,38330,32141,83.9,6189,16.1,4744,12.4,1445,3.8
2,2001,Household composition,With children < 18 years,With children < 6 years,16858,13920,82.6,2938,17.4,2304,13.7,634,3.8
3,2001,Household composition,With children < 18 years,Married-couple families,26182,23389,89.3,2793,10.7,2247,8.6,546,2.1
4,2001,Household composition,With children < 18 years,"Female head, no spouse",9080,6185,68.1,2895,31.9,2101,23.1,794,8.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,2024,Household income-to-poverty ratio,Under 1.00,NaN,11555,6998,60.6,4557,39.4,2526,21.9,2031,17.6
708,2024,Household income-to-poverty ratio,Under 1.30,NaN,16751,10341,61.7,6410,38.3,3692,22.0,2718,16.2
709,2024,Household income-to-poverty ratio,Under 1.85,NaN,28066,18847,67.2,9219,32.8,5465,19.5,3754,13.4
710,2024,Household income-to-poverty ratio,1.85 and over,NaN,78259,72040,92.1,6219,7.9,3876,5.0,2343,3.0
711,2024,Household income-to-poverty ratio,Income unknown,NaN,27736,24833,89.5,2903,10.5,1797,6.5,1106,4.0

In [102]:
all_households_df[all_households_df['category'] == 'All households']['year'].value_counts()

year
2001    1
2002    1
2003    1
2004    1
2005    1
2006    1
2007    1
2008    1
2009    1
2010    1
2011    1
2012    1
2013    1
2014    1
2015    1
2016    1
2017    1
2018    1
2019    1
2020    1
2021    1
2022    1
2023    1
2024    1
Name: count, dtype: int64

In [103]:
us_overall_df = all_households_df[all_households_df['category'] == 'All households'][['year','food_insecure_percent','very_low_food_security_percent']].rename(
    {
        'year':'us_year',
        'food_insecure_percent':'us_food_insecure_pct',
        'very_low_food_security_percent':'us_very_low_food_security_pct'
    },
    axis=1
)

us_overall_df.head()

     us_year  us_food_insecure_pct  us_very_low_food_security_pct
0       2001                  10.7                            3.3
30      2002                  11.1                            3.5
60      2003                  11.2                            3.5
90      2004                  11.9                            3.9
120     2005                  11.0                            3.9

In [104]:
state_us_comparison_df = state_comparison_df.merge(
    us_overall_df,
    left_on='period_end_year',
    right_on='us_year',
    how='left',
    validate='many_to_one'
)

display(state_us_comparison_df)
print(state_us_comparison_df.shape)
print(state_us_comparison_df['us_very_low_food_security_pct'].isna().sum())
print(state_us_comparison_df['us_food_insecure_pct'].isna().sum())
print(state_us_comparison_df['food_insecurity_prevalence'].isna().sum())
print(state_us_comparison_df['very_low_food_security_prevalence'].isna().sum())
print((state_us_comparison_df['us_year'] == state_us_comparison_df['period_end_year']).all())

,year,state,food_insecurity_prevalence,food_insecurity_margin_of_error,very_low_food_security_prevalence,very_low_food_security_margin_of_error,period_start_year,period_end_year,us_year,us_food_insecure_pct,us_very_low_food_security_pct
0,2006–2008,CA,12.0,0.74,4.3,0.48,2006,2008,2008,14.6,5.7
1,2006–2008,IA,11.6,1.15,4.8,0.93,2006,2008,2008,14.6,5.7
2,2006–2008,LA,11.0,1.62,3.7,1.16,2006,2008,2008,14.6,5.7
3,2006–2008,NY,11.3,0.95,4.3,0.46,2006,2008,2008,14.6,5.7
4,2006–2008,TX,16.3,1.08,5.7,0.56,2006,2008,2008,14.6,5.7
...,...,...,...,...,...,...,...,...,...,...,...
80,2022–2024,CA,12.5,0.82,4.4,0.49,2022,2024,2024,13.7,5.4
81,2022–2024,IA,10.8,2.02,3.9,1.07,2022,2024,2024,13.7,5.4
82,2022–2024,LA,17.7,2.29,6.8,1.24,2022,2024,2024,13.7,5.4
83,2022–2024,NY,14.0,1.29,5.6,0.85,2022,2024,2024,13.7,5.4
84,2022–2024,TX,17.6,1.01,6.6,0.63,2022,2024,2024,13.7,5.4

(85, 11)
0
0
0
0
True

In [105]:
educ_analysis_df = educ_emp_dis_df.loc[educ_emp_dis_df['subcategory'] == 'Education',:].rename(
    {
        'sub_subcategory':'education'
    },
    axis=1
).loc[:,['year','education','total','food_insecure_percent','very_low_food_security_percent']]

print(educ_analysis_df.shape)
print(educ_analysis_df.groupby('year').agg({'education':'count'}).reset_index())
print(educ_analysis_df.isna().sum())
print(educ_analysis_df.duplicated(subset=['year','education']).sum())

(32, 5)
   year  education
0  2017          4
1  2018          4
2  2019          4
3  2020          4
4  2021          4
5  2022          4
6  2023          4
7  2024          4
year                              0
education                         0
total                             0
food_insecure_percent             0
very_low_food_security_percent    0
dtype: int64
0

In [106]:
emp_analysis_df = educ_emp_dis_df.loc[educ_emp_dis_df['subcategory'] == 'Employment',:].rename(
    {
        'sub_subcategory':'employment'
    },
    axis=1
).loc[:,['year','employment','total','food_insecure_percent','very_low_food_security_percent']]

print(emp_analysis_df.shape)
print(emp_analysis_df.groupby('year').agg({'employment':'count'}).reset_index())
print(emp_analysis_df.isna().sum())
print(emp_analysis_df.duplicated(subset=['year','employment']).sum())

(56, 5)
   year  employment
0  2017           7
1  2018           7
2  2019           7
3  2020           7
4  2021           7
5  2022           7
6  2023           7
7  2024           7
year                              0
employment                        0
total                             0
food_insecure_percent             0
very_low_food_security_percent    0
dtype: int64
0

In [107]:
dis_analysis_df = educ_emp_dis_df.loc[educ_emp_dis_df['subcategory'] == 'Disability status',:].rename(
    {
        'sub_subcategory':'disability'
    },
    axis=1
).loc[:,['year','disability','total','food_insecure_percent','very_low_food_security_percent']]

print(dis_analysis_df.shape)
print(dis_analysis_df.groupby('year').agg({'disability':'count'}).reset_index())
print(dis_analysis_df.isna().sum())
print(dis_analysis_df.duplicated(subset=['year','disability']).sum())

(32, 5)
   year  disability
0  2017           4
1  2018           4
2  2019           4
3  2020           4
4  2021           4
5  2022           4
6  2023           4
7  2024           4
year                              0
disability                        0
total                             0
food_insecure_percent             0
very_low_food_security_percent    0
dtype: int64
0

In [108]:
# Goal: Compare U.S., Canada, and Mexico undernourishment using World Bank / FAO undernourishment data.
# Keep rows where country is U.S., Canada, or Mexico. I'm not sure what years to include, so we'll use years where all three countries have data.

is_us_can_mex = wb_undernourishment_df['country_code'].isin(['USA','CAN','MEX'])

wb_selected_df = wb_undernourishment_df.loc[is_us_can_mex,:] # TODO: Merge `wb_undernourishment_df`, `wb_country_metadata_df`, `wb_indicator_metadata_df`

wb_selected_df.head()

,country_name,country_code,indicator_name,indicator_code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
35,Canada,CAN,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,NaN,NaN
153,Mexico,MEX,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.7,3.7,3.6,3.4,3.1,3.0,2.8,2.7,NaN,NaN
250,United States,USA,Prevalence of undernourishment (% of population),SN.ITK.DEFC.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,NaN,NaN

In [109]:
year_cols = [s for s in wb_selected_df.columns if s.isdigit()]

In [110]:
wb_melted_df = (
    wb_selected_df.melt(
        id_vars=['country_name','country_code','indicator_name','indicator_code'],
        value_vars=year_cols,
        var_name='year',
        value_name='undernourishment_pct'
    ).dropna(subset='undernourishment_pct')
    .astype({'year':'int64'})
)

In [111]:
print(wb_melted_df.shape)
print(wb_melted_df.columns.tolist())
print('Exactly three countries per year (expect True): ', (wb_melted_df.groupby('year')['country_code'].nunique() == 3).all())  # Expect True
print('More than one row per country per year (expect False): ', wb_melted_df.duplicated(subset=['country_code','year']).any())  # Expect False
print(wb_melted_df.isna().sum())
wb_melted_df.describe()

(69, 6)
['country_name', 'country_code', 'indicator_name', 'indicator_code', 'year', 'undernourishment_pct']
Exactly three countries per year (expect True):  True
More than one row per country per year (expect False):  False
country_name            0
country_code            0
indicator_name          0
indicator_code          0
year                    0
undernourishment_pct    0
dtype: int64

              year  undernourishment_pct
count    69.000000             69.000000
mean   2012.000000              2.856522
std       6.681845              0.563205
min    2001.000000              2.500000
25%    2006.000000              2.500000
50%    2012.000000              2.500000
75%    2018.000000              3.200000
max    2023.000000              4.100000

Expected grain: **one row per country per year.**

## 8. Exploratory Data Analysis

### 8.1 State-to-State Comparison

*How do food insecurity rates differ among California, Texas, Iowa, New York, and Louisiana?*
- Use: `foodsecurity-state-2024.csv`
- Analysis: filter states + compare prevalence rates

### 8.2 State-to-U.S. Comparison

*How do selected states compare with the U.S. overall?*
- Use: `foodsecurity-state-2024.csv` and `foodsecurity-all-households-2024.csv`.
- Analysis: compare each selected state against `U.S. total`

### 8.3 Education Comparison

*How does food insecurity vary by education level in the U.S.?*
- Use: `foodsecurity-educ-emp-dis-2024.csv`.
- Analysis: filter education rows + compare percentages

### 8.4 Employment Comparison

*How does food insecurity vary by employment group in the U.S.?*
- Use: `foodsecurity-educ-emp-dis-2024.csv`.
- Analysis: filter employment rows + compare percentages

### 8.5 Disability Comparison

*How does food insecurity vary by disability status in the U.S.?*
- Use: `foodsecurity-educ-emp-dis-2024.csv`
- Analysis: filter disability rows + compare percentages

### 8.6 World Bank Context

*How does the U.S. compare with Canada and Mexico on undernourishment, and what World Bank metadata can be used to interpret that comparison?*
- Use: World Bank files in `data/raw/world_bank_undernourishment/`
- Analysis: compare the U.S. with Canada and Mexico

#### 8.6.1 How does the U.S. compare with Canada and Mexico on undernourishment?

#### 8.6.2 What World Bank metadata can be used to interpret that comparison?

## 9. Conclusions

## 10. Limitations